######################################################################
# Automatically generated by qmake (2.01a) Mo. Dez 31 21:30:18 2012
######################################################################

TEMPLATE = app
CONFIG = console
TARGET = bin/hyper-qube
DEPENDPATH += . src src/r23d
INCLUDEPATH += . src
CONFIG += link_pkgconfig
PKGCONFIG += ncurses

# Input
HEADERS += src/*.h
SOURCES += src/*.cpp
